import type { NextPage } from "next";
import Head from "next/head";
import AnimateOnView from "../components/animations/ShowOnView";
import textAnimation from "../components/animations/textAnimation";
import Card from "../components/card";
import Light from "../components/light";
import ListCardFiller, { CardListItem } from "../components/listCardFiller";
import Quote from "../components/quote";
import Socials from "../components/socials";
import TextCardFiller from "../components/textCardFiller";
import fs from "fs";
import yaml from "js-yaml";
type HomePageProps = {
  coolStuff: CardListItem[];
  experiences: CardListItem[];
};

const Home = ({ coolStuff, experiences }: HomePageProps) => {
  return (
    <div className="relative h-screen w-screen">
      <Head>
        <title>Lorenzo Romagnoni</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Light height={20} width={20} r={206} g={17} b={255} />
      <Light height={35} width={25} r={47} g={79} b={211} x={0} />
      <Light height={35} width={25} r={17} g={211} b={224} x={100} />
      <div className="tracking-normal ">
        <div className="flex justify-center pt-28 text-2xl ">
          Lorenzo Romagnoni
        </div>
        <div className="font-medium text-center text-zinc-400 leading-7 text-lg mt-3 mx-10">
          web software engineer at{" "}
          <span style={{ color: "#ed34b9" }}>Bending&nbsp;Spoons</span>
          <br></br>
          previously at <span style={{ color: "#ed34b9" }}>tutored</span>
        </div>
      </div>
      <div className="mt-24">
        <AnimateOnView>
          <Card>
            <AnimateOnView variants={textAnimation}>
              <TextCardFiller
                text={`Determined and enterprising developer from Milan, Italy! 🟩⬜🟥
Tech lover👨‍💻 and extremely curious, I always want to learn more from disparate fields: web and mobile development, AI🤖,finance📈, sociology, psychology🧠 and more.
Frequently thinking about my next journey✈️, next projects and goals🏆.
I love reading📘, I think it is the most powerful way to learn from extraordinary people, from all over the world (space🌍) and history (time⌛)!,`}
              />
            </AnimateOnView>
          </Card>
        </AnimateOnView>

        <AnimateOnView>
          <Card>
            <ListCardFiller title="Experiences" items={experiences} />
          </Card>
        </AnimateOnView>

        <AnimateOnView>
          <Card>
            <ListCardFiller title="Cool stuff" items={coolStuff} />
          </Card>
        </AnimateOnView>
      </div>
      <div className="my-24">
        <Quote />
      </div>
      <Socials />
    </div>
  );
};

export async function getStaticProps() {
  const coolStuff = yaml.load(
    fs.readFileSync("./data/coolStuff.yaml", { encoding: "utf-8" })
  ) as CardListItem[];
  const experiences = yaml.load(
    fs.readFileSync("./data/experiences.yaml", { encoding: "utf-8" })
  ) as CardListItem[];
  return {
    props: {
      experiences,
      coolStuff,
    },
  };
}

export default Home;
