import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/card";
import Light from "../components/light";

const Home: NextPage = () => {
  return (
    <div className="relative h-screen w-screen overflow-hidden">
      <Head>
        <title>Lorenzo Romagnoni</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Light height={38} width={30} r={206} g={17} b={255} />
      <Light height={23} width={24} r={47} g={79} b={211} />
      <Light height={25} width={12} r={17} g={211} b={224} />
      <Light height={9} width={86} r={17} g={211} b={224} xTraslation="-50%" />

      <div className="tracking-normal ">
        <div className="flex justify-center pt-28 text-2xl ">
          Lorenzo Romagnoni
        </div>
        <div className="font-medium text-center text-zinc-400 leading-7 text-lg mt-3 mx-10">
          web software engineer at{" "}
          <span style={{ color: "#ed34b9" }}>Bending&nbsp;Spoons</span>
          <br></br>
          previously at <span style={{ color: "#ed34b9" }}>tutored</span>
        </div>
      </div>
      <Card text="Lorem ipsum" />
    </div>
  );
};

export default Home;
